mmbv:
  titleRu: "Индекс ММВБ."
  titleEn: "MICEX Index."
  descRu: "ММВБ        — График ММВБ-индекса."
  descEn: "MICEX     — MICEX index chart."
  buttonRu: "ММВБ"
  buttonEn: "MICEX"
  apiUrl: "https://api.z-lab.me/charts/mmvb.png"
usd_rub:
  titleRu: "Курс USD/RUB по Forex."
  titleEn: "USD/RUB rate from Forex."
  descRu: "USD/RUB     — Текущий курс USD/RUB по Forex."
  descEn: "USD/RUB   — Current USD/RUB rate from Forex."
  buttonRu: "USD/RUB"
  buttonEn: "USD/RUB"
  apiUrl: "https://api.z-lab.me/charts/usd_rub_forex.png"
usd_uah:
  titleRu: "Курс USD/UAH по Nasdaq, NYSE."
  titleEn: "USD/UAH rate from Nasdaq, NYSE."
  descRu: "USD/UAH     — Текущий курс USD/UAH по NYSE."
  descEn: "USD/UAH   — Current USD/UAH rate from NYSE."
  buttonRu: "USD/UAH"
  buttonEn: "USD/UAH"
  apiUrl: "https://api.z-lab.me/charts/usd_uah.png"
eur_rub:
  titleRu: "Курс EUR/RUB по Forex."
  titleEn: "EUR/RUB rate from Forex."
  descRu: "EUR/RUB     — Текущий курс EUR/RUB по Forex."
  descEn: "EUR/RUB   — Current EUR/RUB rate from Forex."
  buttonRu: "EUR/RUB"
  buttonEn: "EUR/RUB"
  apiUrl: "https://api.z-lab.me/charts/rub_eur_forex.png"
eur_usd:
  titleRu: "Курс EUR/UAH по Forex."
  titleEn: "EUR/UAH rate from Forex."
  descRu: "EUR/UAH     — Текущий курс EUR/USD по Forex."
  descEn: "EUR/UAH   — Current EUR/USD rate from Forex."
  buttonRu: "EUR/UAH"
  buttonEn: "EUR/UAH"
  apiUrl: "https://api.z-lab.me/charts/eur_usd_forex.png"
gold:
  titleRu: "Золото по Nasdaq."
  titleEn: "Gold from Nasdaq."
  descRu: "Золото      — Золото по Nasdaq."
  descEn: "Gold      — Gold from Nasdaq."
  buttonRu: "Золото"
  buttonEn: "Gold"
  apiUrl: "https://api.z-lab.me/charts/gold.png"
palladium:
  titleRu: "Палладий по Nasdaq."
  titleEn: "Palladium from Nasdaq."
  descRu: "Палладий    — Палладий по Nasdaq."
  descEn: "Palladium — Palladium from Nasdaq."
  buttonRu: "Палладий"
  buttonEn: "Palladium"
  apiUrl: "https://api.z-lab.me/charts/palladium.png"
platinum:
  titleRu: "Платина по Nasdaq."
  titleEn: "Platinum from Nasdaq."
  descRu: "Платина     — Платина по Nasdaq."
  descEn: "Platinum  — Platinum from Nasdaq."
  buttonRu: "Платина"
  buttonEn: "Platinum"
  apiUrl: "https://api.z-lab.me/charts/platinum.png"
rhodium:
  titleRu: "Родий по Nasdaq."
  titleEn: "Rhodium from Nasdaq."
  descRu: "Родий       — Родий по Nasdaq."
  descEn: "Rhodium   — Rhodium from Nasdaq."
  buttonRu: "Родий"
  buttonEn: "Rhodium"
  apiUrl: "https://api.z-lab.me/charts/rhodium.png"
silver:
  titleRu: "Серебро по Nasdaq."
  titleEn: "Silver from Nasdaq."
  descRu: "Серебро     — Серебро по Nasdaq."
  descEn: "Silver    — Silver from Nasdaq."
  buttonRu: "Серебро"
  buttonEn: "Silver"
  apiUrl: "https://api.z-lab.me/charts/silver.png"
rts:
  titleRu: "Индекс РТС по ММВБ."
  titleEn: "RTS Index from ММВБ (MICEX)."
  descRu: "РТС         — График индекса РТС по ММВБ."
  descEn: "RTS       — RTS Index chart from ММВБ (MICEX)."
  buttonRu: "РТС"
  buttonEn: "RTS"
  apiUrl: "https://api.z-lab.me/charts/rts.png"
btc_usd:
  titleRu: "Курс BTC/USD по WorldCoinIndex."
  titleEn: "BTC/USD rate from WorldCoinIndex."
  descRu: "BTC/USD     — Текущий курс BTC/USD по WCI."
  descEn: "BTC/USD   — Current BTC/USD rate from WCI."
  buttonRu: "BTC/USD"
  buttonEn: "BTC/USD"
  apiUrl: "https://api.z-lab.me/charts/btc_usd.png"
bcc_usd:
  titleRu: "Курс BCC/USD по WorldCoinIndex."
  titleEn: "BCC/USD rate from WorldCoinIndex."
  descRu: "BCC/USD     — Текущий курс BCC/USD по WCI."
  descEn: "BCC/USD   — Current BCC/USD rate from WCI."
  buttonRu: "BCC/USD"
  buttonEn: "BCC/USD"
  apiUrl: "https://api.z-lab.me/charts/bcc_usd.png"
dsh_usd:
  titleRu: "Курс DSH/USD по WorldCoinIndex."
  titleEn: "DSH/USD rate from WorldCoinIndex."
  descRu: "DSH/USD     — Текущий курс DSH/USD по WCI."
  descEn: "DSH/USD   — Current DSH/USD rate from WCI."
  buttonRu: "DSH/USD"
  buttonEn: "DSH/USD"
  apiUrl: "https://api.z-lab.me/charts/dsh_usd.png"
ltc_usd:
  titleRu: "Курс LTC/USD по WorldCoinIndex."
  titleEn: "LTC/USD rate from WorldCoinIndex."
  descRu: "LTC/USD     — Текущий курс LTC/USD по WCI."
  descEn: "LTC/USD   — Current LTC/USD rate from WCI."
  buttonRu: "LTC/USD"
  buttonEn: "LTC/USD"
  apiUrl: "https://api.z-lab.me/charts/ltc_usd.png"
eth_usd:
  titleRu: "Курс ETH/USD по WorldCoinIndex."
  titleEn: "ETH/USD rate from WorldCoinIndex."
  descRu: "ETH/USD     — Текущий курс ETH/USD по WCI."
  descEn: "ETH/USD   — Current ETH/USD rate from WCI."
  buttonRu: "ETH/USD"
  buttonEn: "ETH/USD"
  apiUrl: "https://api.z-lab.me/charts/eth_usd.png"
iota_usd:
  titleRu: "Курс IOTA/USD по WorldCoinIndex."
  titleEn: "IOTA/USD rate from WorldCoinIndex."
  descRu: "IOTA/USD    — Текущий курс IOTA/USD по WCI."
  descEn: "IOTA/USD  — Current IOTA/USD rate from WCI."
  buttonRu: "IOTA/USD"
  buttonEn: "IOTA/USD"
  apiUrl: "https://api.z-lab.me/charts/iota_usd.png"
usd_rub_n:
  titleRu: "Курс USD/RUB по Nasdaq, NYSE."
  titleEn: "USD/RUB rate from Nasdaq, NYSE."
  descRu: "USD/RUB N   — Текущий курс USD/RUB по NYSE."
  descEn: "USD/RUB N — Current USD/RUB rate from NYSE."
  buttonRu: "USD/RUB N"
  buttonEn: "USD/RUB N"
  apiUrl: "https://api.z-lab.me/charts/usd_rub.png"
brent:
  titleRu: "Нефть Brent по Nasdaq, NYSE."
  titleEn: "Brent oil from Nasdaq, NYSE."
  descRu: "Нефть Brent — Нефть Brent USD/BBL по NYSE."
  descEn: "Brent Oil — Brent oil USD/BBL rate from NYSE."
  buttonRu: "Нефть Brent"
  buttonEn: "Brent Oil"
  apiUrl: "https://api.z-lab.me/charts/brent.png"
wti:
  titleRu: "Нефть WTI по Nasdaq, NYSE."
  titleEn: "WTI oil from Nasdaq, NYSE."
  descRu: "Нефть WTI   — Нефть WTI USD/BBL по NYSE."
  descEn: "WTI Oil   — WTI oil USD/BBL rate from NYSE."
  buttonRu: "Нефть WTI"
  buttonEn: "WTI Oil"
  apiUrl: "https://api.z-lab.me/charts/wti.png"
